const dummyUsers = [
  {
    fullName: 'Annabell Widmoor',
    email: 'awidmoor0@pen.io',
    password: 'lfVi8XdklNt',
    street: 'Nova',
    number: 5,
    zip: 17733,
    city: 'Richmond',
    state: 'VA',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Loren Chater',
    email: 'lchater1@about.com',
    password: 'ZUaigfMdB',
    street: 'Hermina',
    number: 3,
    zip: 20970,
    city: 'Topeka',
    state: 'KS',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Darcee Lighton',
    email: 'dlighton2@ehow.com',
    password: 'MO6NaVhbgVM1',
    street: 'Bartillon',
    number: 100,
    zip: 13203,
    city: 'Washington',
    state: 'DC',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Bastian Loddon',
    email: 'bloddon3@youtu.be',
    password: 'E2768vDkqB',
    street: '5th',
    number: 54,
    zip: 61882,
    city: 'Schaumburg',
    state: 'IL',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Nalani Durrans',
    email: 'ndurrans4@apache.org',
    password: 'BNxN8PwQvD',
    street: 'Transport',
    number: 87,
    zip: 96896,
    city: 'Houston',
    state: 'TX',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Vinni Brokenshaw',
    email: 'vbrokenshaw5@auda.org.au',
    password: 'TLTY1F5C',
    street: 'Blaine',
    number: 39,
    zip: 26741,
    city: 'San Antonio',
    state: 'TX',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Harold Kenelin',
    email: 'hkenelin6@si.edu',
    password: 'sDaFlnqi2c',
    street: '4th',
    number: 49,
    zip: 88703,
    city: 'New Orleans',
    state: 'LA',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Krystal Rofe',
    email: 'krofe7@prnewswire.com',
    password: 'rm22cHYSc',
    street: 'Corben',
    number: 86,
    zip: 65969,
    city: 'Oakland',
    state: 'CA',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Bald Ankers',
    email: 'bankers8@deliciousdays.com',
    password: 'UDKi6DP',
    street: 'Arkansas',
    number: 29,
    zip: 32295,
    city: 'Corpus Christi',
    state: 'TX',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Kaitlin Watman',
    email: 'kwatman9@xing.com',
    password: 'auEPWd',
    street: 'Manufacturers',
    number: 27,
    zip: 50186,
    city: 'Saint Paul',
    state: 'MN',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Cosetta Fairman',
    email: 'cfairmana@canalblog.com',
    password: '6XgISAwtkkt',
    street: 'Brickson Park',
    number: 74,
    zip: 44333,
    city: 'Kalamazoo',
    state: 'MI',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Gizela Learoyde',
    email: 'glearoydeb@virginia.edu',
    password: 'jIEwzsymcYyw',
    street: 'Lukken',
    number: 62,
    zip: 99990,
    city: 'Rochester',
    state: 'NY',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Sarita Anglin',
    email: 'sanglinc@instagram.com',
    password: 'lgpRnx',
    street: 'Grasskamp',
    number: 34,
    zip: 65823,
    city: 'White Plains',
    state: 'NY',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Aile Liveley',
    email: 'aliveleyd@hud.gov',
    password: 'Bk1TpVI',
    street: 'Melrose',
    number: 87,
    zip: 88952,
    city: 'Tulsa',
    state: 'OK',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Royall Bignold',
    email: 'rbignolde@discuz.net',
    password: 'wIjrMc7',
    street: 'Nancy',
    number: 57,
    zip: 78256,
    city: 'Birmingham',
    state: 'AL',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Tim Ughelli',
    email: 'tughellif@usnews.com',
    password: 'uz2Hhs',
    street: 'Independence',
    number: 30,
    zip: 59336,
    city: 'San Diego',
    state: 'CA',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Farrell Rimer',
    email: 'frimerg@soundcloud.com',
    password: 'jS3QxkpvH',
    street: 'Fremont',
    number: 76,
    zip: 18734,
    city: 'Tampa',
    state: 'FL',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Odille Charles',
    email: 'ocharlesh@skyrock.com',
    password: 'vRj7vBb',
    street: 'Corry',
    number: 51,
    zip: 87469,
    city: 'Tallahassee',
    state: 'FL',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Harry Jaime',
    email: 'hjaimei@issuu.com',
    password: 'SznI6buo',
    street: 'Moulton',
    number: 86,
    zip: 86875,
    city: 'Minneapolis',
    state: 'MN',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Homer Hurcombe',
    email: 'hhurcombej@cloudflare.com',
    password: 'j0dmlZeak',
    street: 'Bunker Hill',
    number: 25,
    zip: 50143,
    city: 'Cincinnati',
    state: 'OH',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Annabal Le Breton',
    email: 'alek@vistaprint.com',
    password: 'JsroGcn5Y',
    street: 'Nobel',
    number: 25,
    zip: 46625,
    city: 'Miami',
    state: 'FL',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Hyacintha Pettie',
    email: 'hpettiel@mapquest.com',
    password: 'dRSP8RZgHE',
    street: 'Memorial',
    number: 58,
    zip: 99634,
    city: 'Columbus',
    state: 'OH',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Ignacio Gipps',
    email: 'igippsm@jimdo.com',
    password: 'ywZCFS7',
    street: 'Shopko',
    number: 6,
    zip: 92605,
    city: 'Houston',
    state: 'TX',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Zulema Thurner',
    email: 'zthurnern@amazonaws.com',
    password: 'pFjg4X',
    street: 'Tomscot',
    number: 56,
    zip: 98895,
    city: 'Peoria',
    state: 'IL',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Alana Goodhay',
    email: 'agoodhayo@reddit.com',
    password: 'FGtRNXnv',
    street: 'Tennyson',
    number: 80,
    zip: 13606,
    city: 'Panama City',
    state: 'FL',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Robin Sille',
    email: 'rsillep@furl.net',
    password: '7Ib6U7',
    street: 'Forest Run',
    number: 23,
    zip: 80761,
    city: 'Asheville',
    state: 'NC',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Lynnet Blazdell',
    email: 'lblazdellq@marketwatch.com',
    password: 'OVaHTLJJB',
    street: 'Farragut',
    number: 3,
    zip: 88476,
    city: 'Atlanta',
    state: 'GA',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Kean Yakunkin',
    email: 'kyakunkinr@hp.com',
    password: 'UZmbm1DB5P',
    street: 'Magdeline',
    number: 89,
    zip: 57154,
    city: 'Ventura',
    state: 'CA',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Halsey Paye',
    email: 'hpayes@shop-pro.jp',
    password: 'D2nxSGfm',
    street: 'Bobwhite',
    number: 49,
    zip: 52714,
    city: 'Lawrenceville',
    state: 'GA',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Joaquin Archard',
    email: 'jarchardt@cbc.ca',
    password: 'CngL2Unvt9j5',
    street: 'Nobel',
    number: 12,
    zip: 11199,
    city: 'East Saint Louis',
    state: 'IL',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Em Bushnell',
    email: 'ebushnellu@irs.gov',
    password: 'mjslESgKz',
    street: 'Hovde',
    number: 15,
    zip: 78716,
    city: 'Ashburn',
    state: 'VA',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Cristian Romushkin',
    email: 'cromushkinv@vkontakte.ru',
    password: 'C7UiwHHdS',
    street: 'Debra',
    number: 88,
    zip: 50905,
    city: 'Denver',
    state: 'CO',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Rockie Aleshkov',
    email: 'raleshkovw@opera.com',
    password: 'fyoUAv1mO2',
    street: 'Fuller',
    number: 33,
    zip: 89413,
    city: 'Kansas City',
    state: 'MO',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Ly Cicconettii',
    email: 'lcicconettiix@youtu.be',
    password: 'NhHrsx1OhQnY',
    street: 'Heath',
    number: 95,
    zip: 29006,
    city: 'San Antonio',
    state: 'TX',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Adrianne Crusham',
    email: 'acrushamy@kickstarter.com',
    password: 'yaKf5iGyD',
    street: 'Birchwood',
    number: 79,
    zip: 91961,
    city: 'Raleigh',
    state: 'NC',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Clevie Dilliway',
    email: 'cdilliwayz@spiegel.de',
    password: 'CMpYmEQYmoq',
    street: 'Service',
    number: 35,
    zip: 56145,
    city: 'Charleston',
    state: 'WV',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Omero Heiner',
    email: 'oheiner10@hubpages.com',
    password: 'BBhy8ivA0',
    street: 'Fulton',
    number: 24,
    zip: 49915,
    city: 'Greensboro',
    state: 'NC',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Tommi Shemming',
    email: 'tshemming11@techcrunch.com',
    password: 'VtxpuW',
    street: 'Boyd',
    number: 10,
    zip: 11617,
    city: 'Murfreesboro',
    state: 'TN',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Adolph Southgate',
    email: 'asouthgate12@weather.com',
    password: 'xZQGaalGmV',
    street: 'Lakeland',
    number: 58,
    zip: 29883,
    city: 'Harrisburg',
    state: 'PA',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Emlen Rennocks',
    email: 'erennocks13@sina.com.cn',
    password: '54hgJnm2UeDS',
    street: 'Prairieview',
    number: 15,
    zip: 69690,
    city: 'Colorado Springs',
    state: 'CO',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Amie Clissell',
    email: 'aclissell14@infoseek.co.jp',
    password: 'o1pAgI6',
    street: 'Northview',
    number: 2,
    zip: 18975,
    city: 'Minneapolis',
    state: 'MN',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Stanislaw Tomicki',
    email: 'stomicki15@reference.com',
    password: '8frVVO0qI3',
    street: 'Southridge',
    number: 100,
    zip: 80996,
    city: 'Miami',
    state: 'FL',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Humbert Burney',
    email: 'hburney16@reddit.com',
    password: 'BZH625di5',
    street: 'Novick',
    number: 98,
    zip: 24606,
    city: 'Salt Lake City',
    state: 'UT',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Leila Jeffes',
    email: 'ljeffes17@ed.gov',
    password: 'RZNiRkTz',
    street: 'Lunder',
    number: 68,
    zip: 58875,
    city: 'Birmingham',
    state: 'AL',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Adi Bison',
    email: 'abison18@wsj.com',
    password: 'roHS8VkAl0',
    street: 'Clarendon',
    number: 34,
    zip: 68203,
    city: 'Saint Louis',
    state: 'MO',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Ann-marie Isaaksohn',
    email: 'aisaaksohn19@digg.com',
    password: 'AnxRy2A73s',
    street: 'Pawling',
    number: 29,
    zip: 76269,
    city: 'Pittsburgh',
    state: 'PA',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Melody Daines',
    email: 'mdaines1a@yolasite.com',
    password: 'V4B2d7fynrI7',
    street: 'Butterfield',
    number: 2,
    zip: 59757,
    city: 'Denver',
    state: 'CO',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Farley Tomsen',
    email: 'ftomsen1b@dropbox.com',
    password: 'vywCPt',
    street: 'Rigney',
    number: 21,
    zip: 22440,
    city: 'Lancaster',
    state: 'CA',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Stephen Edds',
    email: 'sedds1c@hostgator.com',
    password: '44m67XnhJMN',
    street: 'Claremont',
    number: 100,
    zip: 47700,
    city: 'Shawnee Mission',
    state: 'KS',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Kikelia Prayer',
    email: 'kprayer1d@google.com.br',
    password: '2RqlTMouB5f',
    street: 'Bowman',
    number: 100,
    zip: 98124,
    city: 'Richmond',
    state: 'VA',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Delcine Tilmouth',
    email: 'dtilmouth1e@wikipedia.org',
    password: '6kl0Dzqx',
    street: 'Ramsey',
    number: 16,
    zip: 30474,
    city: 'San Diego',
    state: 'CA',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Benedicta Wanka',
    email: 'bwanka1f@storify.com',
    password: 'c7hpjfoxRilX',
    street: 'Fisk',
    number: 31,
    zip: 44434,
    city: 'Toledo',
    state: 'OH',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Harp Triggs',
    email: 'htriggs1g@webeden.co.uk',
    password: 'ynj5VadPs',
    street: 'Dexter',
    number: 78,
    zip: 34967,
    city: 'Kansas City',
    state: 'MO',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Roseanne Ubach',
    email: 'rubach1h@shareasale.com',
    password: 'ljmUtXz4',
    street: 'Johnson',
    number: 55,
    zip: 81079,
    city: 'Rockville',
    state: 'MD',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Tore Eberdt',
    email: 'teberdt1i@pcworld.com',
    password: 'RUttxOcqZYeF',
    street: 'Novick',
    number: 100,
    zip: 23427,
    city: 'Kansas City',
    state: 'MO',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Violette Winsper',
    email: 'vwinsper1j@cocolog-nifty.com',
    password: 'BOotLXi3qJU',
    street: 'Gerald',
    number: 60,
    zip: 44569,
    city: 'Boise',
    state: 'ID',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Haskel Conquer',
    email: 'hconquer1k@dedecms.com',
    password: 'ZTygOVL',
    street: 'Talmadge',
    number: 52,
    zip: 33646,
    city: 'Young America',
    state: 'MN',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Mari Dunnan',
    email: 'mdunnan1l@netscape.com',
    password: '8sLsYOsgA',
    street: 'Hanson',
    number: 51,
    zip: 19065,
    city: 'Austin',
    state: 'TX',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Caty Leppington',
    email: 'cleppington1m@moonfruit.com',
    password: 'LWssyRo',
    street: 'Burning Wood',
    number: 26,
    zip: 19659,
    city: 'Burbank',
    state: 'CA',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Jeramie Beachamp',
    email: 'jbeachamp1n@wisc.edu',
    password: 'RQLJe6i',
    street: 'Forster',
    number: 89,
    zip: 69644,
    city: 'Lexington',
    state: 'KY',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Clerkclaude Copley',
    email: 'ccopley1o@youtube.com',
    password: 'jfppzyN',
    street: 'Florence',
    number: 18,
    zip: 46926,
    city: 'Conroe',
    state: 'TX',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Fran Varley',
    email: 'fvarley1p@prnewswire.com',
    password: 'ERaSB7',
    street: 'Superior',
    number: 28,
    zip: 49205,
    city: 'Sacramento',
    state: 'CA',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Bary Mulroy',
    email: 'bmulroy1q@163.com',
    password: 'luZhCV',
    street: 'Stuart',
    number: 34,
    zip: 32976,
    city: 'Fort Worth',
    state: 'TX',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Murial Ropcke',
    email: 'mropcke1r@tinyurl.com',
    password: 'msEMfL5',
    street: 'Homewood',
    number: 6,
    zip: 98178,
    city: 'Kansas City',
    state: 'MO',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Fredelia Enden',
    email: 'fenden1s@squidoo.com',
    password: 'KYBZCWn',
    street: 'Goodland',
    number: 89,
    zip: 19076,
    city: 'Huntsville',
    state: 'AL',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Donal MacAdie',
    email: 'dmacadie1t@yellowpages.com',
    password: 'EXD8WhFq',
    street: 'Farragut',
    number: 86,
    zip: 99039,
    city: 'Los Angeles',
    state: 'CA',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Claiborne Berston',
    email: 'cberston1u@washington.edu',
    password: 'GRU7r7CBB4Z',
    street: 'Lakewood',
    number: 60,
    zip: 69869,
    city: 'New York City',
    state: 'NY',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Birgitta Mogridge',
    email: 'bmogridge1v@prnewswire.com',
    password: 'mvPi5RR3xMYi',
    street: 'Forest Run',
    number: 81,
    zip: 64554,
    city: 'Austin',
    state: 'TX',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Lutero Baud',
    email: 'lbaud1w@smugmug.com',
    password: 'afdD4pJVt',
    street: 'Hanson',
    number: 63,
    zip: 55966,
    city: 'Saint Cloud',
    state: 'MN',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Davidson Ziehm',
    email: 'dziehm1x@slideshare.net',
    password: 'nlkXrS3Ne',
    street: 'Browning',
    number: 13,
    zip: 83320,
    city: 'New York City',
    state: 'NY',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Carlita Kane',
    email: 'ckane1y@examiner.com',
    password: 'NOua8iAugcp',
    street: 'Village Green',
    number: 46,
    zip: 74882,
    city: 'Orange',
    state: 'CA',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Ripley Greenfield',
    email: 'rgreenfield1z@gravatar.com',
    password: 'eRpksX7sp',
    street: 'John Wall',
    number: 90,
    zip: 83905,
    city: 'Palmdale',
    state: 'CA',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Isa Mosdell',
    email: 'imosdell20@cafepress.com',
    password: 'mZerGW6Ox2qN',
    street: 'Chinook',
    number: 51,
    zip: 27516,
    city: 'Dallas',
    state: 'TX',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Genovera Gath',
    email: 'ggath21@dell.com',
    password: '8MNZrg4uLonW',
    street: 'Lawn',
    number: 26,
    zip: 74632,
    city: 'Charlotte',
    state: 'NC',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Stephie Sampson',
    email: 'ssampson22@myspace.com',
    password: 'tD5dDlC',
    street: 'Hanover',
    number: 18,
    zip: 42959,
    city: 'Newton',
    state: 'MA',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Jennica Shovlin',
    email: 'jshovlin23@narod.ru',
    password: 'KG80ESLv',
    street: 'Buena Vista',
    number: 8,
    zip: 96587,
    city: 'Pompano Beach',
    state: 'FL',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Akim Blare',
    email: 'ablare24@msu.edu',
    password: 'zOAQjSjamm',
    street: 'Hazelcrest',
    number: 38,
    zip: 18831,
    city: 'Littleton',
    state: 'CO',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Mitzi Gansbuhler',
    email: 'mgansbuhler25@stanford.edu',
    password: 'MHNqMqwMg9C',
    street: 'Raven',
    number: 43,
    zip: 93031,
    city: 'Nashville',
    state: 'TN',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Lianne Meharg',
    email: 'lmeharg26@sakura.ne.jp',
    password: '4R587UEwBE',
    street: 'Maryland',
    number: 83,
    zip: 76340,
    city: 'Birmingham',
    state: 'AL',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Lynne Lawlance',
    email: 'llawlance27@hhs.gov',
    password: 'yOKwsIKP',
    street: 'Hollow Ridge',
    number: 3,
    zip: 10619,
    city: 'Baltimore',
    state: 'MD',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Karlens Harmar',
    email: 'kharmar28@tiny.cc',
    password: 'vTIe6TvP5',
    street: 'Hoepker',
    number: 8,
    zip: 91120,
    city: 'Jefferson City',
    state: 'MO',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Tove Simak',
    email: 'tsimak29@pagesperso-orange.fr',
    password: '49b9aFhYJ65A',
    street: 'Washington',
    number: 37,
    zip: 49623,
    city: 'Washington',
    state: 'DC',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Christal Prue',
    email: 'cprue2a@studiopress.com',
    password: 'JX1NKhMpz4',
    street: 'Ridgeway',
    number: 5,
    zip: 35774,
    city: 'Missoula',
    state: 'MT',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Estelle Ragge',
    email: 'eragge2b@washingtonpost.com',
    password: 'ikMDj5vjHndv',
    street: 'Vermont',
    number: 97,
    zip: 28345,
    city: 'Lawrenceville',
    state: 'GA',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Gorden Buddleigh',
    email: 'gbuddleigh2c@ameblo.jp',
    password: 'JqBrWMxS8',
    street: 'Sycamore',
    number: 74,
    zip: 51755,
    city: 'Chicago',
    state: 'IL',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Westbrook Fitzsimon',
    email: 'wfitzsimon2d@github.io',
    password: 'oUpHNqvM3FS',
    street: 'Golf',
    number: 12,
    zip: 15019,
    city: 'Ocala',
    state: 'FL',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Langsdon Liddel',
    email: 'lliddel2e@upenn.edu',
    password: 'odTjGfM',
    street: 'Acker',
    number: 92,
    zip: 99859,
    city: 'Gadsden',
    state: 'AL',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Silvan Jewess',
    email: 'sjewess2f@vk.com',
    password: 'fes9529DMwM',
    street: 'Burrows',
    number: 53,
    zip: 81747,
    city: 'Punta Gorda',
    state: 'FL',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Denny Prestidge',
    email: 'dprestidge2g@ebay.co.uk',
    password: 'vLio0bLh',
    street: 'Jackson',
    number: 52,
    zip: 81101,
    city: 'Atlanta',
    state: 'GA',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Dyna Beazer',
    email: 'dbeazer2h@forbes.com',
    password: 'MkxB5g72v3fl',
    street: 'Reinke',
    number: 64,
    zip: 72061,
    city: 'Salt Lake City',
    state: 'UT',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Clerkclaude Zold',
    email: 'czold2i@hatena.ne.jp',
    password: 'rb029Hw5',
    street: 'Johnson',
    number: 49,
    zip: 21620,
    city: 'Baltimore',
    state: 'MD',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Mollee Lawleff',
    email: 'mlawleff2j@people.com.cn',
    password: 'CJg706',
    street: 'Sommers',
    number: 66,
    zip: 92602,
    city: 'Salt Lake City',
    state: 'UT',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Wiatt Freke',
    email: 'wfreke2k@redcross.org',
    password: '5MwJeWR',
    street: 'Mariners Cove',
    number: 43,
    zip: 87018,
    city: 'Lexington',
    state: 'KY',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Gwynne Dike',
    email: 'gdike2l@mac.com',
    password: 'K3veRj2h',
    street: 'Kipling',
    number: 58,
    zip: 33403,
    city: 'Phoenix',
    state: 'AZ',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Fletch Arnoldi',
    email: 'farnoldi2m@sogou.com',
    password: '0hj20y',
    street: 'Magdeline',
    number: 35,
    zip: 61511,
    city: 'Erie',
    state: 'PA',
    country: 'US',
    isAdmin: true,
    googleId: 99999
  },
  {
    fullName: 'Ellissa Huffa',
    email: 'ehuffa2n@twitter.com',
    password: 'BrvwfST',
    street: 'Northwestern',
    number: 71,
    zip: 43652,
    city: 'White Plains',
    state: 'NY',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Dar Kauble',
    email: 'dkauble2o@gnu.org',
    password: 'ub313UAOWvYC',
    street: 'Spenser',
    number: 12,
    zip: 15808,
    city: 'Minneapolis',
    state: 'MN',
    country: 'US',
    isAdmin: false,
    googleId: 99999
  },
  {
    fullName: 'Sonya Ramelet',
    email: 'sramelet2p@census.gov',
    password: '6IA3HkoMLRf',
    street: 'Mariners Cove',
    number: 100,
    zip: 23276,
    city: 'Long Beach',
    state: 'CA',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  },
  {
    fullName: 'Cassie Pencot',
    email: 'cpencot2q@tiny.cc',
    password: '7QEgmN7t',
    street: 'Valley Edge',
    number: 14,
    zip: 25816,
    city: 'Vancouver',
    state: 'WA',
    country: 'US',
    isAdmin: true,
    googleId: 100000
  },
  {
    fullName: 'Carter Flight',
    email: 'cflight2r@narod.ru',
    password: 'jwMsMfC9y',
    street: 'Tomscot',
    number: 40,
    zip: 30486,
    city: 'Lincoln',
    state: 'NE',
    country: 'US',
    isAdmin: false,
    googleId: 100000
  }
]
module.exports = dummyUsers
